import inspect
import os
import sys

current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
# Ensure both repo root and tests directory are on sys.path
sys.path.insert(0, parent_dir)
sys.path.insert(0, current_dir)

# Banking System
from banking_system.level_1_tests import BankingSystemLevel1Tests as SandboxBankingSystemLevel1Tests
from banking_system.level_2_tests import BankingSystemLevel2Tests as SandboxBankingSystemLevel2Tests
from banking_system.level_3_tests import BankingSystemLevel3Tests as SandboxBankingSystemLevel3Tests
from banking_system.level_4_tests import BankingSystemLevel4Tests as SandboxBankingSystemLevel4Tests

# Integer Container
from integer_container.level_1_tests import Level1Tests as SandboxIntegerContainerLevel1Tests
from integer_container.level_2_tests import Level2Tests as SandboxIntegerContainerLevel2Tests

# File Storage System
from file_storage_system.level_1_tests import FileStorageSystemLevel1Tests as SandboxFileStorageSystemLevel1Tests
from file_storage_system.level_2_tests import FileStorageSystemLevel2Tests as SandboxFileStorageSystemLevel2Tests
from file_storage_system.level_3_tests import FileStorageSystemLevel3Tests as SandboxFileStorageSystemLevel3Tests
from file_storage_system.level_4_tests import FileStorageSystemLevel4Tests as SandboxFileStorageSystemLevel4Tests

# Text Editor
from text_editor.level_1_tests import TextEditorLevel1Tests as SandboxTextEditorLevel1Tests
from text_editor.level_2_tests import TextEditorLevel2Tests as SandboxTextEditorLevel2Tests
from text_editor.level_3_tests import TextEditorLevel3Tests as SandboxTextEditorLevel3Tests
from text_editor.level_4_tests import TextEditorLevel4Tests as SandboxTextEditorLevel4Tests

# Time Tracking System
from time_tracking_system.level_1_tests import TimeTrackingSystemLevel1Tests as SandboxTimeTrackingSystemLevel1Tests
from time_tracking_system.level_2_tests import TimeTrackingSystemLevel2Tests as SandboxTimeTrackingSystemLevel2Tests
from time_tracking_system.level_3_tests import TimeTrackingSystemLevel3Tests as SandboxTimeTrackingSystemLevel3Tests
from time_tracking_system.level_4_tests import TimeTrackingSystemLevel4Tests as SandboxTimeTrackingSystemLevel4Tests

# Course System
from course_system.level_1_tests import CourseSystemLevel1Tests as SandboxCourseSystemLevel1Tests
from course_system.level_2_tests import CourseSystemLevel2Tests as SandboxCourseSystemLevel2Tests
from course_system.level_3_tests import CourseSystemLevel3Tests as SandboxCourseSystemLevel3Tests
from course_system.level_4_tests import CourseSystemLevel4Tests as SandboxCourseSystemLevel4Tests

# Database
from database.level_1_tests import DatabaseLevel1Tests as SandboxDatabaseLevel1Tests
from database.level_2_tests import DatabaseLevel2Tests as SandboxDatabaseLevel2Tests
from database.level_3_tests import DatabaseLevel3Tests as SandboxDatabaseLevel3Tests
from database.level_4_tests import DatabaseLevel4Tests as SandboxDatabaseLevel4Tests

# In-Memory DB
from in_memory_db.level_1_tests import InMemoryDBLevel1Tests as SandboxInMemoryDBLevel1Tests
from in_memory_db.level_2_tests import InMemoryDBLevel2Tests as SandboxInMemoryDBLevel2Tests
from in_memory_db.level_3_tests import InMemoryDBLevel3Tests as SandboxInMemoryDBLevel3Tests
from in_memory_db.level_4_tests import InMemoryDBLevel4Tests as SandboxInMemoryDBLevel4Tests
